package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/google/uuid"
	"github.com/vitormoschetta/go-graphql/graph/generated"
	"github.com/vitormoschetta/go-graphql/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input generated.ProductInput) (*model.Product, error) {
	ID := uuid.New().String()
	product, err := r.ProductDB.Create(ID, input.Name, *input.Description, input.CategoryID, input.Price)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:          product.ID,
		Name:        product.Name,
		Description: &product.Description,
		Price:       product.Price,
	}, nil
}

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *model.Product) (*model.Category, error) {
	category, err := r.CategoryDB.FindByProductID(obj.ID)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		ID:          category.ID,
		Name:        category.Name,
		Description: &category.Description,
	}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.ProductDB.GetAll()
	if err != nil {
		return nil, err
	}

	var result []*model.Product
	for _, product := range products {
		result = append(result, &model.Product{
			ID:          product.ID,
			Name:        product.Name,
			Description: &product.Description,
			Price:       product.Price,
		})
	}

	return result, nil
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
